from flask import Flask, render_template, request, jsonify
import tejas

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/processUserData', methods=['POST'])
def process_user_data():
    data = request.json  # Get data sent from the web page

    # Retrieve data from the request
    name = data.get('name')
    language = data.get('language')
    age = data.get('age')
    blood_group = data.get('bloodGroup')
    health_disease = data.get('healthDisease')
    allergy = data.get('allergy')
    weight = data.get('weight')
    selected_issues = data.get('selectedIssues')

    # Set the data into the Tkinter variables
    tejas.name_var.set(name)
    tejas.language_var.set(language)
    tejas.age_var.set(age)
    tejas.blood_group_var.set(blood_group)
    tejas.health_disease_var.set(health_disease)
    tejas.allergy_var.set(allergy)
    tejas.weight_var.set(weight)
    # You can set the selected issues into Tkinter variables similarly

    # Start the Tkinter application logic
    tejas.start_questionnaire()

    # Retrieve the results generated by the Tkinter app
    results = tejas.get_results()  # Implement this function in your tejas.py

    return jsonify({'message': results})

if __name__ == '__main__':
    app.run(debug=True)
